<?php
/**
 * Created by PhpStorm.
 * User: Sabuj
 * Date: 8/11/15
 * Time: 12:11 AM
 */

class UrlRules {

        public static $urlManager = array(
                'urlFormat'=>'path',
                'showScriptName'=>false,
                'rules'=>array(
                    'feedback' => 'site/ReceiveFeedback',
                    'portal-excel' => 'site/Excel',
                    'userProfile'=>'profile/userProfile',
                    'all-ads'=>'profile/userProfile',
                    'forget-password'=>'site/forgetPassword',
                    'add-post'=> 'site/postYourAdd',
                    'sign-in'=>'site/SignIn',
                    'add-post-details'=>'site/DetailsAdPost',
                    'admin-panel'=>'site/login',
                    'logout'=>'site/logout',
                    'category-script'=>'site/categoryScript',
                    'portal-declined-payment'=>'site/ShowPaymentPortalForDeclinedTransaction',
                    'portal'=>'site/ShowPaymentPortal',
                    'portal-create'=>'site/PortalCreate',
                    'portal-login'=>'site/DoPortalLogin',
                    'portal-logout'=>'site/DoPortalLogout',
                    'global-links'=>'site/ShowGlobalLinks',
                    'list'=>'profile/list',
                    'grid'=>'profile/grid',
                    'ad'=>'site/ad',
                    'ad-post-success' => 'site/SaveAd',
                    'update-ad' => 'site/EditAd',
                    
                    'delete-ad' => 'site/DeleteAd',
                    'help'=>'site/help',
                    'how-it-works'=>'site/GetHowItWorksPage',
                    'recently-viewed-ad' => 'category/getRecentlyViewedAds',
                    'contact-us'=>'site/contact',
                    'success'=>'site/success',
                    'update-success'=>'site/updateSuccess',
                    'job-post-success' => 'site/jobPostSuccess',
                    'ad-list' => 'category/listAd',
                    'search' => 'site/Search',
                    'show-all' => 'site/ShowAll',
                    'advertise-with-us' => 'site/PricePlan',
                    'price-plan-details' => 'site/PricePlanDetails',
                    'terms-&-conditions' => 'site/TermsConditions',
                    'estore-activation' => 'site/ActivateEStore',
                    'estore-creation-from-support' => 'site/CreateEStoreFromSupport',
                    'promotion-banner-creation-from-support' => 'site/CreateBannerFromSupport',
                    'career' => 'site/Career',
                    'job-details' => 'site/jobDetails',
                    'registration-confirm' => 'site/otpConfirmation',
                    'special-offer' => 'site/specialOffer',
                    'expire-soon-ads' => 'site/expireSoonAds',
                    'service/the_hobs' => 'service/ShowEducationTemplate',
                    'service/medicale' => 'service/ShowMedicalTemplate',
                    'service/<service_url>' => 'service/index',
                    'promotion/<page_alias>' => 'site/promotion',
                    'promotions/<page_alias_ad_special>' => 'site/promotions',
                    'my-profile/update-e-store' => 'profile/UpdateEStore',
                    'my-profile/update-isp' => 'profile/UpdateIsp',
                    'my-profile/update-isp-ad' => 'profile/EditISPPackage',
                    'my-profile/update-estore-ad' => 'profile/EditEstoreProduct',
                    'my-profile/service-information' => 'profile/GetServiceInformation',
                    'my-profile/change-plan'=>'profile/ChangePlan',
                    'my-profile/dashboard'=>'profile/YourDashboard',
                    'my-profile/my-ads'=>'profile/MyAds',
                    'my-profile/my-packages'=>'profile/MyPackages',
                    'my-profile/messages'=>'profile/Messages',
                    'my-profile/messages/<message_type>'=>'profile/Messages',
                    'my-profile/favourite-ads'=>'profile/ListFavouriteAds',
                    'my-profile/my-searches'=>'profile/MySearches',
                    'my-profile/notifications'=>'profile/Notifications',
                    'my-profile/settings'=>'profile/settings',
                    'my-profile/create-e-store'=>'profile/CreateEStore',
                    'my-profile/business-information'=>'profile/BusinessInformation',
                    'my-profile/business-information-with-post-service'=>'profile/BusinessInformationWithPostService',
                    'my-profile/payment-selection'=>'profile/PaymentSelection',
                    'my-profile/transaction-status'=>'profile/TransactionStatus',
                    'my-profile/add-ads'=>'profile/AddAds',
                    'my-profile/add-package'=>'profile/AddPackage',
                    'my-profile/discount-offer'=>'profile/DiscountOffer',
                    'my-profile/special-ads'=>'profile/specialAds',
                    'my-profile/view-my-e-store'=>'profile/ViewMyEStore',
                    'my-profile/thank-you'=>'profile/ShowThanksMessage',
                    'my-profile/order-management'=>'profile/OrderManagement',
                    'my-profile/payment-processor'=>'profile/PaymentProcessor',
                    'my-profile/transaction-failure'=>'profile/TransactionFailure',
                    'my-profile/transaction-cancel'=>'profile/TransactionCancel',
                    'my-profile/banner-management'=>'profile/ManageBanner',
                    'my-profile/website-management'=>'profile/ManageWebsite',
                    'my-profile/landing-page-management'=>'profile/ManageLandingPage',
                    'my-profile/jobs'=>'profile/ManageJobs',
                    'my-profile/add-job'=>'profile/AddJobs',
                    
                    'e-store/estore-order-confirm' => 'estore/OrderConfirmation',
                    'e-store/<company_name>/all-products' => 'estore/AllProducts',
                    'e-store/<company_name>/product-details/<product_id>' => 'estore/productDetails',
                    'e-store/<company_name>' => 'estore/index',
                    'e-store/<company_name>/contact-us' => 'estore/Contact',
                    'e-store/<company_name>/about-us' => 'estore/About',

                    'isp/isp-order-confirm' => 'isp/OrderConfirmation',
                    'isp/<company_name>/all-products' => 'isp/AllProducts',
                    'isp/<company_name>/package-details/<product_id>' => 'isp/productDetails',
                    'isp/<company_name>' => 'isp/index',
                    'isp/<company_name>/contact-us' => 'isp/Contact',
                    'isp/<company_name>/about-us' => 'isp/About',

                    '<controller:\w+>/<id:\d+>'=>'<controller>/view',
                    '<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
                    '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
                ),
        );
} 